function TunelIndex(info) {
    tub(info);
}


function Video(url) {
    //alert(url);

    var i = 0;
    var vetor = new Array();
    for (i = 0; i < 41; i++)
        vetor[i] = new Array();

    vetor[0][0] = "z1aEQhvsFAQ";
    vetor[0][1] = "Paulinho Moska ";
    vetor[0][2] = " - Provavelmente Você";
    vetor[1][0] = "zocxTQjcR9w";
    vetor[1][1] = "Nielson Alves ";
    vetor[1][2] = " - Café Amargo";
    vetor[2][0] = "nQ84WtdxcIo";
    vetor[2][1] = "Céu";
    vetor[2][2] = " - Eu amo Você";
    vetor[3][0] = "7Qqtqj1odfw";
    vetor[3][1] = "Tiago Iorc";
    vetor[3][2] = " - Story of a Man";
    vetor[4][0] = "-Lb557lk060";
    vetor[4][1] = "Tiago Iorc";
    vetor[4][2] = " - Nothing But a Song";
    vetor[5][0] = "NnTkVZCxHHs";
    vetor[5][1] = "John Mayer";
    vetor[5][2] = " - Gravity";
    vetor[6][0] = "1EHGHzgq72Y";
    vetor[6][1] = "Falamansa";
    vetor[6][2] = " - Indiferente-Xote ecológico";
    vetor[7][0] = "5ejLWCE_esg";
    vetor[7][1] = "Maria Gadú";
    vetor[7][2] = " - Lanterna dos afogados";
    vetor[8][0] = "KiPGXOP2dbg";
    vetor[8][1] = "Vanessa da Mata";
    vetor[8][2] = " - Viagem";
    vetor[9][0] = "OTgZovD03EU";
    vetor[9][1] = "Luciana Mello";
    vetor[9][2] = " - Simples Desejo";
    vetor[10][0] = "CrAti3aG1a8";
    vetor[10][1] = "João Sabiá";
    vetor[10][2] = " - Biriba";
    vetor[11][0] = "Ijb2ZMPxRoI";
    vetor[11][1] = "Roberta Sá e Ney Matogrosso";
    vetor[11][2] = " - Peito Vazio";
    vetor[12][0] = "rw3bXJgqKnc";
    vetor[12][1] = "SOJA";
    vetor[12][2] = " - Not Done Yet";
    vetor[13][0] = "iy7X1clA640";
    vetor[13][1] = "Leo Fressato";
    vetor[13][2] = " - Não há nada mais lindo";
    vetor[14][0] = "FX9s_RfEzJE";
    vetor[14][1] = "Cícero";
    vetor[14][2] = " - Tempo de Pipa";
    vetor[15][0] = "dCJMbcIheFs";
    vetor[15][1] = "Pitty";
    vetor[15][2] = " - Dançando";
    vetor[16][0] = "z9ZLZpcUS0o";
    vetor[16][1] = "Adriana Calcanhotto ";
    vetor[16][2] = " - Do fundo do meu coração";
    vetor[17][0] = "pNdo6ZCCTTo";
    vetor[17][1] = "Paulinho Moska e Milton Nascimento";
    vetor[17][2] = " - Nos bailes da vida";
    vetor[18][0] = "bQXpH83xO8w";
    vetor[18][1] = "João Sabiá";
    vetor[18][2] = " - Mesmo que seja longe";
    vetor[19][0] = "W6H_4YAF4zI";
    vetor[19][1] = "Caetano Veloso";
    vetor[19][2] = " - Voce é linda";
    vetor[20][0] = "P7mHf-UCZp0";
    vetor[20][1] = "Chico Buarque";
    vetor[20][2] = " - Construção";
    vetor[21][0] = "a60fJzqh0NE";
    vetor[21][1] = "Paula Lima ";
    vetor[21][2] = " - Agua de beber";
    vetor[22][0] = "BiacOLRsQtM";
    vetor[22][1] = "Ponto de Equilíbrio";
    vetor[22][2] = " - Aonde Vai Chegar";
    vetor[23][0] = "ZMVawc1TWpM";
    vetor[23][1] = "Natiruts ";
    vetor[23][2] = " - Quero Ser Feliz Também";
    vetor[24][0] = "j44DmnBR_08";
    vetor[24][1] = "Thiago Thomé";
    vetor[24][2] = " - Da Pele Preta";
    vetor[25][0] = "8MKtAbQPMWU";
    vetor[25][1] = "Chimarruts";
    vetor[25][2] = " - Em busca da fé";
    vetor[26][0] = "lk-2xoJ_FJ4";
    vetor[26][1] = "Chimarruts";
    vetor[26][2] = " - O Outono";
    vetor[27][0] = "TYY7KVgLS_A";
    vetor[27][1] = "Onze:20";
    vetor[27][2] = " - Não Vai Voltar";
    vetor[28][0] = "ZQHnlPhovf8";
    vetor[28][1] = "Onze:20";
    vetor[28][2] = " - Nossa Canção";
    vetor[29][0] = "qQdJGKUwcNE";
    vetor[29][1] = "Djavan ";
    vetor[29][2] = " - Faltando um Pedaço";
    vetor[30][0] = "o7w5TsVOoQI";
    vetor[30][1] = "Marcelo Jeneci";
    vetor[30][2] = " - Pra sonhar";
    vetor[31][0] = "l2-aGZ0DWWA";
    vetor[31][1] = "Djavan";
    vetor[31][2] = " - Cair em si";
    vetor[32][0] = "rev2G-7ktYI";
    vetor[32][1] = "Djavan";
    vetor[32][2] = " - Doidice";
    vetor[33][0] = "JzmS0ShC5nE";
    vetor[33][1] = "Maria Gadú";
    vetor[33][2] = " - Tudo diferente";
    vetor[34][0] = "t_BfvzGHJGA";
    vetor[34][1] = "5 a seco e Maria Gadú";
    vetor[34][2] = " - em paz";
    vetor[35][0] = "wWs2dqKRgdI";
    vetor[35][1] = "O Teatro Mágico";
    vetor[35][2] = " - Nosso Pequeno Castelo";
    vetor[36][0] = "w63Aqyht2Cg";
    vetor[36][1] = "Vanessa Da Mata";
    vetor[36][2] = " - Amado";
    vetor[37][0] = "dHEtbkzpI_8";
    vetor[37][1] = "Vanessa Da Mata";
    vetor[37][2] = " - Palavras";
    vetor[38][0] = "sKSEOMy0_wE";
    vetor[38][1] = "Natiruts";
    vetor[38][2] = " - Pérola Negra";
    vetor[39][0] = "y9cRw23bbnk";
    vetor[39][1] = "Paulinho Moska";
    vetor[39][2] = " - Somente nela";
    vetor[40][0] = "DHCQBsyJ_jE";
    vetor[40][1] = "Moska e Lisandro";
    vetor[40][2] = " - Waiting for the Sun to Shine";

    var options = { videoId: vetor, start: 0 };
    $('#wrapper').tubular(options);
}


$('document').ready(function () {

    // $("#telaPrincipal").load('http://www.google.com');

    /*
    var i = 0;
    var vetor = new Array();
    for (i = 0; i < 41; i++)
        vetor[i] = new Array();

    vetor[0][0] = "z1aEQhvsFAQ";
    vetor[0][1] = "Paulinho Moska ";
    vetor[0][2] = " - Provavelmente Você";
    vetor[1][0] = "zocxTQjcR9w";
    vetor[1][1] = "Nielson Alves ";
    vetor[1][2] = " - Café Amargo";
    vetor[2][0] = "nQ84WtdxcIo";
    vetor[2][1] = "Céu";
    vetor[2][2] = " - Eu amo Você";
    vetor[3][0] = "7Qqtqj1odfw";
    vetor[3][1] = "Tiago Iorc";
    vetor[3][2] = " - Story of a Man";
    vetor[4][0] = "-Lb557lk060";
    vetor[4][1] = "Tiago Iorc";
    vetor[4][2] = " - Nothing But a Song";
    vetor[5][0] = "NnTkVZCxHHs";
    vetor[5][1] = "John Mayer";
    vetor[5][2] = " - Gravity";
    vetor[6][0] = "1EHGHzgq72Y";
    vetor[6][1] = "Falamansa";
    vetor[6][2] = " - Indiferente-Xote ecológico";
    vetor[7][0] = "5ejLWCE_esg";
    vetor[7][1] = "Maria Gadú";
    vetor[7][2] = " - Lanterna dos afogados";
    vetor[8][0] = "KiPGXOP2dbg";
    vetor[8][1] = "Vanessa da Mata";
    vetor[8][2] = " - Viagem";
    vetor[9][0] = "OTgZovD03EU";
    vetor[9][1] = "Luciana Mello";
    vetor[9][2] = " - Simples Desejo";
    vetor[10][0] = "CrAti3aG1a8";
    vetor[10][1] = "João Sabiá";
    vetor[10][2] = " - Biriba";
    vetor[11][0] = "Ijb2ZMPxRoI";
    vetor[11][1] = "Roberta Sá e Ney Matogrosso";
    vetor[11][2] = " - Peito Vazio";
    vetor[12][0] = "rw3bXJgqKnc";
    vetor[12][1] = "SOJA";
    vetor[12][2] = " - Not Done Yet";
    vetor[13][0] = "iy7X1clA640";
    vetor[13][1] = "Leo Fressato";
    vetor[13][2] = " - Não há nada mais lindo";
    vetor[14][0] = "FX9s_RfEzJE";
    vetor[14][1] = "Cícero";
    vetor[14][2] = " - Tempo de Pipa";
    vetor[15][0] = "dCJMbcIheFs";
    vetor[15][1] = "Pitty";
    vetor[15][2] = " - Dançando";
    vetor[16][0] = "z9ZLZpcUS0o";
    vetor[16][1] = "Adriana Calcanhotto ";
    vetor[16][2] = " - Do fundo do meu coração";
    vetor[17][0] = "pNdo6ZCCTTo";
    vetor[17][1] = "Paulinho Moska e Milton Nascimento";
    vetor[17][2] = " - Nos bailes da vida";
    vetor[18][0] = "bQXpH83xO8w";
    vetor[18][1] = "João Sabiá";
    vetor[18][2] = " - Mesmo que seja longe";
    vetor[19][0] = "W6H_4YAF4zI";
    vetor[19][1] = "Caetano Veloso";
    vetor[19][2] = " - Voce é linda";
    vetor[20][0] = "P7mHf-UCZp0";
    vetor[20][1] = "Chico Buarque";
    vetor[20][2] = " - Construção";
    vetor[21][0] = "a60fJzqh0NE";
    vetor[21][1] = "Paula Lima ";
    vetor[21][2] = " - Agua de beber";
    vetor[22][0] = "BiacOLRsQtM";
    vetor[22][1] = "Ponto de Equilíbrio";
    vetor[22][2] = " - Aonde Vai Chegar";
    vetor[23][0] = "ZMVawc1TWpM";
    vetor[23][1] = "Natiruts ";
    vetor[23][2] = " - Quero Ser Feliz Também";
    vetor[24][0] = "j44DmnBR_08";
    vetor[24][1] = "Thiago Thomé";
    vetor[24][2] = " - Da Pele Preta";
    vetor[25][0] = "8MKtAbQPMWU";
    vetor[25][1] = "Chimarruts";
    vetor[25][2] = " - Em busca da fé";
    vetor[26][0] = "lk-2xoJ_FJ4";
    vetor[26][1] = "Chimarruts";
    vetor[26][2] = " - O Outono";
    vetor[27][0] = "TYY7KVgLS_A";
    vetor[27][1] = "Onze:20";
    vetor[27][2] = " - Não Vai Voltar";
    vetor[28][0] = "ZQHnlPhovf8";
    vetor[28][1] = "Onze:20";
    vetor[28][2] = " - Nossa Canção";
    vetor[29][0] = "qQdJGKUwcNE";
    vetor[29][1] = "Djavan ";
    vetor[29][2] = " - Faltando um Pedaço";
    vetor[30][0] = "o7w5TsVOoQI";
    vetor[30][1] = "Marcelo Jeneci";
    vetor[30][2] = " - Pra sonhar";
    vetor[31][0] = "l2-aGZ0DWWA";
    vetor[31][1] = "Djavan";
    vetor[31][2] = " - Cair em si";
    vetor[32][0] = "rev2G-7ktYI";
    vetor[32][1] = "Djavan";
    vetor[32][2] = " - Doidice";
    vetor[33][0] = "JzmS0ShC5nE";
    vetor[33][1] = "Maria Gadú";
    vetor[33][2] = " - Tudo diferente";
    vetor[34][0] = "t_BfvzGHJGA";
    vetor[34][1] = "5 a seco e Maria Gadú";
    vetor[34][2] = " - em paz";
    vetor[35][0] = "wWs2dqKRgdI";
    vetor[35][1] = "O Teatro Mágico";
    vetor[35][2] = " - Nosso Pequeno Castelo";
    vetor[36][0] = "w63Aqyht2Cg";
    vetor[36][1] = "Vanessa Da Mata";
    vetor[36][2] = " - Amado";
    vetor[37][0] = "dHEtbkzpI_8";
    vetor[37][1] = "Vanessa Da Mata";
    vetor[37][2] = " - Palavras";
    vetor[38][0] = "sKSEOMy0_wE";
    vetor[38][1] = "Natiruts";
    vetor[38][2] = " - Pérola Negra";
    vetor[39][0] = "y9cRw23bbnk";
    vetor[39][1] = "Paulinho Moska";
    vetor[39][2] = " - Somente nela";
    vetor[40][0] = "DHCQBsyJ_jE";
    vetor[40][1] = "Moska e Lisandro";
    vetor[40][2] = " - Waiting for the Sun to Shine";

    var options = { videoId: vetor, start: 0 };
    $('#wrapper').tubular(options);
    */

    // f-UGhWj1xww cool sepia hd
    // 49SKbS7Xwf4 beautiful barn sepia
});

